Controllers/StaticController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using Vconnect.Common;
using Vconnect.Models;
using System.Drawing;
using System.Drawing.Imaging;
using System.Drawing.Drawing2D;
using System.Drawing.Text;
using System.Data.SqlClient;
using System.Data;
using System.Data.Entity.Infrastructure;
using MailChimp.Types;


namespace Vconnect.Controllers
{
    public class StaticController : Controller
    {
        UserSession objUS = new UserSession();
        //
        // GET: /Static/
        //string sourceurl = string.Empty;
        //string previousurl = string.Empty;
        public void bannerclick(string sourceurl, string previousurl)
        {
            try
            {
                if (Request.QueryString["url"] != null)
                {
                    if (TempData.Peek("source") != null && Request.QueryString["url"].ToString().Trim() == TempData.Peek("source").ToString())
                    {
                        sourceurl = TempData.Peek("source") != null ? TempData.Peek("source").ToString() : "";
                        previousurl = TempData.Peek("previous") != null ? TempData.Peek("previous").ToString() : "";

                        TempData.Keep("source");
                        TempData.Keep("previous");
                    }
                    else if (TempData.Peek("sourcehome") != null && Request.QueryString["url"].ToString().Trim() == TempData.Peek("sourcehome").ToString())
                    {
                        sourceurl = TempData.Peek("sourcehome") != null ? TempData.Peek("sourcehome").ToString() : "";
                        previousurl = TempData.Peek("previoushome") != null ? TempData.Peek("previoushome").ToString() : "";

                        TempData.Keep("sourcehome");
                        TempData.Keep("previoushome");
                    }
                    else if (TempData.Peek("sourcelisting") != null && Request.QueryString["url"].ToString().Trim() == TempData.Peek("sourcelisting").ToString())
                    {
                        sourceurl = TempData.Peek("sourcelisting") != null ? TempData.Peek("sourcelisting").ToString() : "";
                        previousurl = TempData.Peek("previouslisting") != null ? TempData.Peek("previouslisting").ToString() : "";

                        TempData.Keep("sourcelisting");
                        TempData.Keep("previouslisting");
                    }
                    else if (TempData.Peek("sourcedetail") != null && Request.QueryString["url"].ToString().Trim() == TempData.Peek("sourcedetail").ToString())
                    {
                        sourceurl = TempData.Peek("sourcedetail") != null ? TempData.Peek("sourcedetail").ToString() : "";
                        previousurl = TempData.Peek("previousdetail") != null ? TempData.Peek("previousdetail").ToString() : "";

                        TempData.Keep("sourcedetail");
                        TempData.Keep("previousdetail");
                    }
                }

                if (Request.QueryString["id"] != null)
                {

                    //Check if user agent is not search engine Crawler
                    if (!System.Web.HttpContext.Current.Request.Browser.Crawler)
                    {
                        SearchListWEBController searchList = new SearchListWEBController();
                        //int userid = (!string.IsNullOrEmpty(objUS.SV_VCLoginID)) ? Convert.ToInt32(objUS.SV_VCUserContentID) : 0;
                        int userid = (Request != null && !string.IsNullOrEmpty(objUS.SV_VCUserContentID)) ? Convert.ToInt32(objUS.SV_VCUserContentID) : (System.Web.HttpContext.Current.Request != null && !string.IsNullOrEmpty(objUS.SV_VCUserContentID)) ? Convert.ToInt32(objUS.SV_VCUserContentID) : 0;
                        Int64 id = 0;
                        long chk;
                        if (long.TryParse(Request.QueryString["id"].ToString(), out chk))
                        {
                            id = Convert.ToInt64(Request.QueryString["id"].ToString());
                        }

                        

                        searchList.BannerClickLogwithSource(Convert.ToInt32(Request.QueryString["id"].ToString()), System.Web.HttpUtility.HtmlDecode(sourceurl), System.Web.HttpUtility.HtmlDecode(previousurl));
                        
                    }
                    //return Response.Write(System.String.Format("window.open('{0}','_blank')", Request["link"].ToString().Replace("$", "&")));
                    //this.ClientScript.RegisterStartupScript(this.GetType(), this.GetType().Name, string.Format("window.open('{0}', '_blank');", Request["link"].ToString().Replace("$", "&")), true);
                     
                     //Response.RedirectPermanent(Request["link"].ToString().Replace("$", "&"), false);

                    string newUrl = Request["link"].ToString().Replace("$", "&");
                    Response.Clear(); Response.ClearContent(); Response.Status = "301 Moved Permanently";
                    Response.AddHeader("Location", newUrl.Trim()); Response.End();
                    //Write(System.String.Format("window.open('{0}','_blank')", Request["link"].ToString().Replace("$", "&")));
                }
                else
                {
                    Redirect(ConfigurationManager.AppSettings["WebsiteRawPath"].ToString());
                }
            }
            finally
            {
            }
        }
        //public ActionResult bannerclick(string sourceurl,string previousurl)
        //{
        //    try
        //    {
        //        if (Request.QueryString["url"] != null)
        //        {
        //            if (TempData.Peek("source") != null && Request.QueryString["url"].ToString().Trim() == TempData.Peek("source").ToString())
        //            {
        //                sourceurl = TempData.Peek("source") != null ? TempData.Peek("source").ToString() : "";
        //                previousurl = TempData.Peek("previous") != null ? TempData.Peek("previous").ToString() : "";

        //                TempData.Keep("source");
        //                TempData.Keep("previous");
        //            }
        //            else if (TempData.Peek("sourcehome") != null && Request.QueryString["url"].ToString().Trim() == TempData.Peek("sourcehome").ToString())
        //            {
        //                sourceurl = TempData.Peek("sourcehome") != null ? TempData.Peek("sourcehome").ToString() : "";
        //                previousurl = TempData.Peek("previoushome") != null ? TempData.Peek("previoushome").ToString() : "";

        //                TempData.Keep("sourcehome");
        //                TempData.Keep("previoushome");
        //            }
        //            else if (TempData.Peek("sourcelisting") != null && Request.QueryString["url"].ToString().Trim() == TempData.Peek("sourcelisting").ToString())
        //            {
        //                sourceurl = TempData.Peek("sourcelisting") != null ? TempData.Peek("sourcelisting").ToString() : "";
        //                previousurl = TempData.Peek("previouslisting") != null ? TempData.Peek("previouslisting").ToString() : "";

        //                TempData.Keep("sourcelisting");
        //                TempData.Keep("previouslisting");
        //            }
        //            else if (TempData.Peek("sourcedetail") != null && Request.QueryString["url"].ToString().Trim() == TempData.Peek("sourcedetail").ToString())
        //            {
        //                sourceurl = TempData.Peek("sourcedetail") != null ? TempData.Peek("sourcedetail").ToString() : "";
        //                previousurl = TempData.Peek("previousdetail") != null ? TempData.Peek("previousdetail").ToString() : "";

        //                TempData.Keep("sourcedetail");
        //                TempData.Keep("previousdetail");
        //            }
        //        }
            
        //        if (Request.QueryString["id"] != null)
        //        {

        //            //Check if user agent is not search engine Crawler
        //            if (!System.Web.HttpContext.Current.Request.Browser.Crawler)
        //            {
        //                SearchListWEBController searchList = new SearchListWEBController();
        //                //int userid = (!string.IsNullOrEmpty(objUS.SV_VCLoginID)) ? Convert.ToInt32(objUS.SV_VCUserContentID) : 0;
        //                int userid = (Request != null && !string.IsNullOrEmpty(objUS.SV_VCUserContentID)) ? Convert.ToInt32(objUS.SV_VCUserContentID) : (System.Web.HttpContext.Current.Request != null && !string.IsNullOrEmpty(objUS.SV_VCUserContentID)) ? Convert.ToInt32(objUS.SV_VCUserContentID) : 0;
        //                Int64 id = 0;
        //                long chk;
        //                if (long.TryParse(Request.QueryString["id"].ToString(), out chk))
        //                {
        //                    id = Convert.ToInt64(Request.QueryString["id"].ToString());
        //                }
                       
        //                //sourceurl = TempData["sourceURL"] != null ? TempData["sourceURL"].ToString() : "";
        //                //previousurl = TempData["previousURL"] != null ? TempData["previousURL"].ToString() : "";


        //                //sourceurl = TempData["source"] != null ? TempData["sourcelisting"].ToString() : "";
        //                //previousurl = TempData["previous"] != null ? TempData["previous"].ToString() : "";

        //                //TempData.Keep("source");
        //                //TempData.Keep("previous");

        //                //sourceurl = TempData.Peek("source") != null ? TempData.Peek("source").ToString() : "";

Views/Static/404.cshtml
@{
    string vconnect_404=Vconnect.Common.MyGlobalVariables.Staticimage+"vconnect-404-sketch.png";
   ViewBag.Title = "404 Error ";
   Layout = "~/Views/Shared/_WEBMainMasterNew.cshtml";
   string title = "Not Found 404 Page";
   string description = "The Page You Are looking for was not found. Don't worry our map will help to get you to the right place.";
   string keyword = "error page";
   string robots = "noindex,nofollow";  }
@section title{@title}
@section  description{@description}
@section keyword{@keyword}
@section robots{@robots}

<div class="not-found-content row">
   
      <h1>404</h1>
     
       <img src="@vconnect_404" alt="404" />
        <p>Whoops! It seems something broke. <a href="/">here</a></p>
     <p> The address has changed or doesn't exist.</p>
     <a class="button button-red" href="/">Back to the homepage</a>        
 </div>

Views/Static/About.cshtml
@{
    ViewBag.Title = "About";
   Layout = "~/Views/Shared/_WEBMainMasterNew.cshtml";
 }
@section title{@Html.Raw("About Us | VConnect™")}
@section  description{@("VConnect™ the name of topmost Nigerian business directory and Search engine where you can found all Products, Services and Business information. We have created a benchmark due to our best services.")}
@section keyword{@("about vconnect , Nigerian business directory, Nigerian Local Search Engine, about us, company information, top company profile")}
<div class="about-content">
				<div class="sjumbotron">
					<div class="sjumbotron-content row">
						<div class="title-container columns medium-7 medium-centered">
							<h1 class="on-image nexa-bold large">About Us</h1>
							<!-- <p>Take advantage of the multiple channels provided to enable you add value to your business. Engage with prospective customers on VConnect.</p> -->
              <p>Four years back, we started with an ambitious project of organizing information on local businesses in Nigeria and making it available to our users. Today, over 800,000 businesses are closer to their customers and we still have a long way to go. </p>
						</div>
					</div>
				</div>
				<div class="our-mission">
					<div class="our-mission-content row">
						<h2>Our Mission</h2>
						<p class="green">Our mission is to make it easier for everyone to find information on local businesses and to contribute to the growth of small and medium enterprises.</p>
					</div>
				</div>
				<div class="what-we-do">
					<div class="row what-we-do-content">
						<div class="columns medium-12">
							<h2>What We Do</h2>
							<div class="row">
								<div class="columns medium-6 ">
									<!-- <h3>Users Gain Point</h3> -->
									<p>We provide our users with a large number of businesses listed on our website from which they can benefit. Our users can see the business' location on the map, get their contact details and see their products and services. All this information is also accessible on the go through our mobile website and mobile apps platforms.</p>
								</div>
								<div class="columns medium-6 ">
									<!-- <img src="img/lab.jpg" alt=""> -->
									<p>We connect local businesses with their potential customers. Businesses benefit from our efficient and cost effective marketing tools to reach out to even wider audience.</p>
                                    <a href="http://vconnect.com/BusinessSolutions" class="red-link">Learn more about our business solutions &rarr;</a>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="quote">
					<h2>Words from our customers</h2>
					<div class="row quote-content">
						<blockquote>Since I have subscribed VConnect, all my sales and marketing campaigns are done digitally on VConnect platform. I no longer need to jump around for sales bidding. Most of my sales come from referral calls from VConnect users. I get business calls regularly from this platform. I recommend VConnect to any serious minded business owners. Cheers!!! VConnect.<cite>Denis Iheadiri, CEO, Excellence Awards International.</cite></blockquote>
					</div>
					<div class="row quote-content">
						<blockquote>My Business has benefitted from VConnect’s excellent Customer Relationship Management Team. Vconnect has been attentive to my specific request in terms of product listing, given timely feedback for prospects enquiries, and over the years has created more visibility for my business. <cite>Taiwo Giwa Idris, CEO, Fire Inhibitors And Home Safety Limited.</cite></blockquote>
					</div>
				</div>
				<div class="our-team">
					<div class="row our-team-content">
						<h2>Our Team</h2>
						<!-- <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae, itaque, architecto, sequi quo repellat neque veritatis error ut nesciunt similique autem minus molestias in quibusdam saepe placeat iusto nam odit?</p> -->
					</div>
					<div class="team-photo">
						<div class="team-photo-content row">
							<p>‘We are VConnectors’</p>
						</div>
					</div>
				</div>
				<div class="our-products">
					<div class="row">
						<div class="columns medium-12">
							<p class="lead">We build a platform to remove the barriers between you and the business information you want.</p>
						</div>
					</div>
					<div class="our-product-content row">
						<div class="columns medium-6">
              <!-- <p>We provide you with the ability to still get whatever information you need regardless of your current time and location. With our easy-to-use mobile site and mobile apps for smartphones, required business information is super easy and stress-free.</p> -->
              <p>Finding business information has never been easy in Nigeria. Over the past four years, we have nurtured a database of over 800,000 businesses in Nigeria so that our users can freely access this information. We connect our users to businesses around them.</p>
              <p>Growth of internet in Nigeria has been unlike any other country in the world. Mobile internet continues to be more popular amongst our users. We make it easy for our users to access information on location, product &amp; services on-the-go. Our mobile site and Mobile app compliment our website. 
              <p>We strive to deliver a consistent, meaningful and engaging experience to our users across all the three platforms.</p>
						</div>
					</div>
				</div>
				<!-- <div class="our-features">
					<div class="row our-features-content">
						<h2>Our Features</h2>
						<ul class="medium-block-grid-3">
							<li>
								<img src="img/lab-line.png" alt="image">
								<h4>Search</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipisiciarchitecto quaerat!<br><a href="#">Learn more &rarr;</a></p>
							</li>
							<li>
								<img src="img/lab-line.png" alt="image">
								<h4>Post Requirement</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipisiciarchitecto quaerat!<br><a href="#">Learn more &rarr;</a></p>
							</li>
							<li>
								<img src="img/lab-line.png" alt="image">
								<h4>Business Forum</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipisiciarchitecto quaerat!<br><a href="#">Learn more &rarr;</a></p>
							</li>
							<li>
								<img src="img/lab-line.png" alt="image">
								<h4>Business Solutions</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipisiciarchitecto quaerat!<br><a href="#">Learn more &rarr;</a></p>
							</li>
							<li>
								<img src="img/lab-line.png" alt="image">
								<h4>Register Your Business</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipisiciarchitecto quaerat!<br><a href="#">Learn more &rarr;</a></p>
							</li>
							<li>
								<img src="img/lab-line.png" alt="image">
								<h4>Claim Your Business</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipisiciarchitecto quaerat!<br><a href="#">Learn more &rarr;</a></p>
							</li>
							<li>
								<img src="img/lab-line.png" alt="image">
								<h4>Advertise With Us</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipisiciarchitecto quaerat!<br><a href="#">Learn more &rarr;</a></p>
							</li>
							<li>
								<img src="img/lab-line.png" alt="image">
								<h4>Get Business Online</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipisiciarchitecto quaerat!<br><a href="#">Learn more &rarr;</a></p>
							</li>
							<li>
								<img src="img/lab-line.png" alt="image">
								<h4>Feedback</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipisiciarchitecto quaerat!<br><a href="#">Learn more &rarr;</a></p>
							</li>
						</ul>
					</div>
				</div> -->
				<div class="press">
					<div class="row press-content">
						VConnect in the press and media.
						<p class="lead">See what the press is saying about us. <a href="http://www.vconnect.com/pressrelease">Visit our press and media page &rarr;</a></p>
					</div>
				</div>
			</div>   

Views/Static/Contactus.cshtml
@model  Vconnect.Models.StaticPagesModel
@{
   Layout = "~/Views/Shared/_WEBMainMasterNew.cshtml";
   string title = "Contact Us - Share Your Ideas to Improve Our Offering | VConnect™";//your page title
   string description = "Share your ideas to improve our offering. Feel free to ask any queries related to business information. Call on our Tele Search number 070 0000 8888 or mail us at info@vconnect.com to get answers for your questions.";
   string keyword = "Contact VConnect™ , VConnect Contact details, VConnect contact addresses, VConnect tele search number, vconnect phone number";
 }
@section title{@title}
@section  description{@description}
@section keyword{@keyword}
 <script>

     function isNumberKey(evt) {
         // debugger;
         var charCode = (evt.which) ? evt.which : event.keyCode;
         if (charCode != 46 && charCode > 31
           && (charCode < 48 || charCode > 57))
             return false;
         return true;
     }
     $(function () {
         $('#phonenumber').blur(function () {
             $.getJSON('/Static/phonenumbercheck', { phonenumber: $("#phonenumber").val() },
             function (data) {
                 // document.getElementById('txtContactPersonPhone').style.display = 'none';
                 document.getElementById('Msgavailablebusinessphonenol').style.display = 'block';
                 document.getElementById("Msgavailablebusinessphoneno").innerHTML = '';
                 document.getElementById('Labelloaderphone').innerHTML = 'Checking ...';
                 document.getElementById("divnf2").style.display = 'block';

                 // alert(document.getElementById('divnf1').innerHTML);

                 if (data == '2') {
                     document.getElementById('Labelloaderphone').innerHTML = '';
                     document.getElementById('Msgavailablebusinessphonenol').style.display = 'none';
                     document.getElementById("Msgavailablebusinessphoneno").innerHTML = 'Invalid Phone Number';
                     document.getElementById('Msgavailablebusinessphoneno').style.color = 'white';
                     document.getElementById('Msgavailablebusinessphoneno').style.display = 'block';

                 }

                 else if (data == '5') {
                     document.getElementById('Labelloaderphone').innerHTML = '';
                     document.getElementById('Msgavailablebusinessphonenol').style.display = 'none';
                     document.getElementById("Msgavailablebusinessphoneno").innerHTML = 'Please start contact number with zero';
                     document.getElementById('Msgavailablebusinessphoneno').style.color = 'white';
                     document.getElementById('Msgavailablebusinessphoneno').style.display = 'block';
                 }
                 else {
                     document.getElementById('Labelloaderphone').innerHTML = '';
                     document.getElementById('Msgavailablebusinessphonenol').style.display = 'none';
                     document.getElementById("Msgavailablebusinessphoneno").innerHTML = '';
                     document.getElementById('Msgavailablebusinessphoneno').style.display = 'none';
                 }
             }
                 )
         });
     });


        </script>
 <script lang="javascript" type="text/javascript">
     $(document).ready(function () {
         $("#txtEmail").change(function (evt) {
             var x = document.getElementById('txtEmail').value;
             var atpos = x.indexOf("@@");
             var dotpos = x.lastIndexOf(".");
             if (atpos < 1 || dotpos < atpos + 2 || dotpos + 2 >= x.length) {
                 document.getElementById("MsgtxtEmail").innerHTML = 'invaild Email-Id';
                 document.getElementById('MsgtxtEmail').style.color = 'white';
                 document.getElementById('MsgtxtEmail').style.display = 'block';
             }
             else {
                 document.getElementById("MsgtxtEmail").innerHTML = '';
                 document.getElementById('MsgtxtEmail').style.display = 'none';
                 document.getElementById('lblemail').style.color = 'black';
             }
             if (x == "") {
                 document.getElementById("MsgtxtEmail").innerHTML = '';
                 document.getElementById('MsgtxtEmail').style.display = 'none';
             }
         });
         $("#phonenumber").change(function (evt) {
             if (document.getElementById("Msgavailablebusinessphoneno").innerHTML != "") {
                 document.getElementById("Msgavailablebusinessphoneno").innerHTML = '';
                 document.getElementById('Msgavailablebusinessphoneno').style.display = 'none';
             }
         });
     });
            </script>
			<div class="contact-content">
                 
        <div class="heading-bg-box">
            <div class="row">

             <div class="alerts">       
       @if (ViewBag.message != null)
      {
          <div data-alert class="alert-box">
                        <!-- Your content goes here -->
                         @ViewBag.message
               <a href="#" class="close">&times;</a>
           </div><br/>
      }
      else if (ViewBag.message1 != null)
                     {
           <div data-alert class="alert-box error">
                        @ViewBag.message1
                         <a href="#" class="close">&times;</a>
          </div>
                     }
      else
      {
       <div></div>
      }
                </div> 

            </div>
         <div class="heading-box">
           <h1 class="on-image nexa-bold text-center">Contact Us</h1>
         </div>
       </div>
       <div class="row contact-form-container">

          <div class="columns medium-6 contact-form">
          <h4>Write Us a Note</h4>
           <form method="post" data-abide>
              @* @using (Ajax.BeginForm("Contactus", "Static", new AjaxOptions { UpdateTargetId = "alertmsg", OnComplete = "complete" },new { data_abide=""}))
               {
            *@<div class="input-wrapper">
              <label for="fname">Your Name <small class="red">Required</small></label>
                @Html.TextBoxFor(model => model.Contactus.name, new { id = "fname", @maxlength = "30", @placeholder = "Your Name", @data_invalid = "", @required = "" })
                <small class="error">Enter your name</small>
            </div>
            <div class="input-wrapper">
              <label for="email">Your Email Address <small class="red">Required</small></label>
                 @Html.TextBoxFor(model => model.Contactus.email, new { id = "txtEmail", @placeholder = "Your Email Address", @data_invalid = "", @required = "", @pattern = "email" })
                <small id="MsgtxtEmail" class="error">Enter your email address</small>
            </div>
            <div class="input-wrapper">
              <label for="phone">Phone <small>Optional</small></label>
                 @Html.TextBoxFor(model => model.Contactus.phoneno, new { id = "phonenumber", onkeypress = "return isNumberKey(event)", maxlength = "11", @placeholder = "Your Phone number" })
             
                <small id="Msgavailablebusinessphoneno" class="error"></small>       
                <div id="Msgavailablebusinessphonenol" style="display: none;">
                                    <img src="~/Images/WEB/logos/allpageloader.gif" alt="Processing..." />
                                    <div class="bizuser_loadertxt">
                                        <label id="Labelloaderphone">
                                        </label>
                                    </div>
                                </div>
                        <div id="divnf2" class="Msgavailablebusiness"></div>  
            </div>
            <div class="input-wrapper">
              <label for="message">Your Message <small class="red">Required</small></label>
                @Html.TextAreaFor(model => model.Contactus.message, new { id = "message", @placeholder = "Your Message", @data_invalid = "", @required = "", @cols = "30", @rows = "10" })
              
              <small class="error">Enter your message</small>
            </div>
               <input type="submit" onclick="$('#alertmsg')[0].focus()" value="Submit" class="button button-red small radius" />
               @*//}*@
          </form>
         </div>
         <div class="columns medium-6 quick-contacts">
            <div class="qcontact-item">
               <h4>Partnerships</h4>
               <p>You think we can do business together. Let us know how at .<br>
               <a href="mailto:marketing@vconnect.co">marketing@vconnect.com</a></p>
            </div>
            <div class="qcontact-item">
               <h4>Subscriptions</h4>
               <p>Thinking of VConnect subscription, drop us a line at<br>
               <a href="mailto:sales@vconnect.com">Sales@vconnect.com</a></p>
            </div>
            <div class="qcontact-item">
               <h4>Already Subscribed</h4>
               <p>Tell us about your updates and concerns at.<br>
               <a href="mailto:business@vconnect.com">business@vconnect.com</a></p>
            </div>
            <div class="qcontact-item">
               <h4>Share with Us</h4>
               <p>Have something to share with us but don't know where. No Wahala. Send at <br>
               <a href="mailto:info@vconnect.com">info@vconnect.com</a></p>
            </div>
         </div>
       </div>
       <div class="row">
         <div class="columns medium-12 contact-map-container">
          <div id="contact-map" class="contact-map"></div>
         </div>
       </div>
      </div>
        <script src="https://maps.googleapis.com/maps/api/js?v=3&sensor=false"></script>
        @*<script src="~/js/min/contact.map.min.js"></script>*@

Views/Static/PressRelease.cshtml
@{
    ViewBag.Title = "PressRelease";
    Layout = "~/Views/Shared/_WebMainMasterNew.cshtml";
    string title = "Press Release - Company News & Information | VConnect™";//your page title
    string description = "Find the latest company news headlines and latest information and Updates at Vconnect.com";
    string keyword = "Press release, company news, vconnect updates, vconnect information";
 }
@section title{@title}
@section  description{@description}
@section keyword{@keyword}
<div style="text-align: center;">
		<iframe  style=" border: none;margin-top: 20px;" id='myframe' src='http://static.vconnect.com/pressrelease/' width="974"
			height="1450"></iframe>
	</div>