Controllers/UserDashboardWEBController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vconnect.Models;
using System.Data.SqlClient;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Web.Helpers;
using Vconnect.Common;
using System.Text.RegularExpressions;
using System.Drawing.Drawing2D;
using System.Drawing;
using System.Net;
using System.Net.Mail;
using System.Configuration;
using Facebook;
using Newtonsoft.Json.Linq;
using DotNetOpenAuth.AspNet;
using Microsoft.Web.WebPages.OAuth;
using adamprescott.net.TweetConsole;
using System.Text;
using System.Security.Cryptography;
using Google.GData.Client;
using Google.GData.Contacts;
using Google.Contacts;
using System.Runtime.Serialization.Json;
using DotNetOpenAuth.Messaging;
using SD = System.Drawing;
using MailChimp.Types;
namespace Vconnect.Controllers
{
    public class UserDashboardWebController : Controller
    {
        private static string locState = string.Empty, locSearchLocation = string.Empty;
        private string rturl = string.Empty;
        int UserId = 0;
        string oauth_consumer_key = ConfigurationManager.AppSettings["twitterAppID"].ToString().Trim(); // "96ZV9fuJQnQLdrRSSWJdVQ";
        string oauth_consumer_secret = ConfigurationManager.AppSettings["twitterAppSecret"].ToString().Trim();
        string oauth_token = "";
        string oauth_token_secret = "";
        private TwitterConsumer _twitter;
        private string clientID = ConfigurationManager.AppSettings["gmailclientid"].ToString().Trim();
        private string clientSecret = ConfigurationManager.AppSettings["gmailclientsecret"].ToString().Trim();
        private string redirectURIs = ConfigurationManager.AppSettings["gmailredirecturl"].ToString().Trim();
        public string strTwiterFollowers { get; set; }
        public string strTwiterFriends { get; set; }
        public string authHeader = string.Empty;
        public string resource_url = string.Empty;
        private string url;
        private GoogleId gId;
        UserSession objUS = new UserSession();
        //
        // GET: /UserDashboardWEB/
        #region image path
        public string webconfigSourceImagesRootPath = ConfigurationManager.AppSettings["SourceImagesRootPath"].ToString();
        public string webconfigDestinationImagesRootPath = ConfigurationManager.AppSettings["DestinationImagesRootPath"].ToString();
        #endregion
        public ActionResult Index()
        {
            return View();
        }
        

        #region change password

        [HttpGet]
        public ActionResult WebChangePassword()
        {
            UserDashboardWebModel UserDbWEBModel = new UserDashboardWebModel();
            Int32 userid = 0;
            if (!string.IsNullOrEmpty(objUS.SV_VCUserContentID))
            {
                userid = Convert.ToInt32(objUS.SV_VCUserContentID.ToString());
                UserDbWEBModel.UserId = userid;
            }
            else
            {
                return RedirectToAction("Login", "Account", new { rturl = "UserDashboardWeb/UserDetailsWeb" });
            }
            return View();
        }

        [HttpPost]
        public ActionResult WebChangePassword(UserDashboardWebModel UserDbWEBModel, FormCollection form)
        {

            Int32 userid = 0;
            string msg = string.Empty;
            try
            {
                if (!string.IsNullOrEmpty(objUS.SV_VCUserContentID))
                {
                    userid = Convert.ToInt32(objUS.SV_VCUserContentID.ToString());
                    UserDbWEBModel.UserId = userid;
                }
                int result = 0;

                string pwd = form["pwd"].ToString();
                string confirmpwd = form["confirmpwd"].ToString();
                // UserDashboardWebModel UserDbWEBModel = new UserDashboardWebModel();
                if (UserDbWEBModel.changePassword.OldPassword == null || UserDbWEBModel.changePassword.OldPassword == "")
                {
                    msg = "Please enter old password";
                    ViewBag.msg = "Please enter old password";
                }

                else
                    if (pwd == null || pwd == "")
                    {
                        msg = "Please enter new  password";
                        ViewBag.msg = "Please enter new  password";
                    }
                    else
                        if (confirmpwd == null || confirmpwd == "")
                        {
                            msg = "Plesae enter confirm password";
                            ViewBag.msg = "Plesae enter confirm password";
                        }
                if (pwd != null && UserDbWEBModel.changePassword.OldPassword != null && confirmpwd != null)
                {
                    if (pwd != confirmpwd)
                    {
                        msg = "New Password And Confirm Password must be equal";

                    }
                    else
                    {
                        result = UserDbWEBModel.WebChangePassword(UserDbWEBModel.changePassword, pwd);
                        if (result == 0)
                        {
                            msg = "Password Updated Successfully..Thankyou";
                        }
                        else if (result == 2)
                        {
                            msg = "Old Password does not match! try again.";
                        }
                        else
                        {
                            msg = "An error occurred. Please try again.";
                        }
                    }

                }
            }
            catch (Exception ex)
            {
                log.LogMe(ex);
            }
            return Content(msg);
        }

        #endregion

        #region validaion
        [AcceptVerbs(HttpVerbs.Get)]
        public JsonResult GetProductByCategory(int? Stateid)
        {
            //return Json(Vconnect.Common.Utility.GetSelectListCity(Stateid.Value), JsonRequestBehavior.AllowGet);
            if (Stateid.HasValue)
            {
                return Json(Vconnect.Common.Utility.GetSelectListCity(Stateid.Value), JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(null, JsonRequestBehavior.AllowGet);
            }
        }

        //for client side phone and alternate phone number check
        [AcceptVerbs(HttpVerbs.Get)]
        public JsonResult phonenumbercheck(string phonenumber)
        {
            int d = 4;
            if (!string.IsNullOrEmpty(phonenumber.Trim().TrimEnd().TrimStart()) && !string.IsNullOrWhiteSpace(phonenumber.Trim().TrimEnd().TrimStart()))
            {
                int result = Vconnect.Common.Utility.isValidPhone(phonenumber);

                string sContactNumber = phonenumber;
                string subSection = sContactNumber.Substring(0, 1);

                //if (subSection != "0")
                //{
                //    d = 3;
                //}
                //else if (result == 0)
                //{
                //    d = 2;
                //}
                if (result == 0)
                {
                    d = 2;
                }
                else
                {
                    d = 4;
                }
            }
            else
            {
                d = 4;
            }

            return Json(d, JsonRequestBehavior.AllowGet);
        }


        //for client side email and alternate email check
        [AcceptVerbs(HttpVerbs.Get)]
        public JsonResult emailcheck(string email)
        {
            int d = 5;
            Regex rgx = new Regex(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*");
            if (!string.IsNullOrEmpty(email.Trim().TrimEnd().TrimStart()) && !string.IsNullOrWhiteSpace(email.Trim().TrimEnd().TrimStart()))
            {
                if (!rgx.IsMatch(email))
                {
                    d = 1;
                }
            }
            else
            {
                d = 5;
            }
            return Json(d, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Get all the Users Infomation
        public ActionResult UserDetailsWeb()
        {
            Int32 userid = 0;
            UserDashboardWebModel UserDbWEBModel = new UserDashboardWebModel();
            if (!string.IsNullOrEmpty(objUS.SV_VCUserContentID))
            {
                userid = Convert.ToInt32(objUS.SV_VCUserContentID.ToString());
                UserDbWEBModel.UserId = userid;
                return RedirectToAction("getUserDetails", new { userid = userid });
            }
            else
            {
                return RedirectToAction("Login", "Account", new { rturl = "UserDashboardWeb/UserDetailsWeb" });
            }
            // return View(UserDbWEBModel);
        }
        //public ActionResult getUserDetails(Int64 userid)
        //{
        //    UserDashboardWebModel UserDbWEBModel = new UserDashboardWebModel();
        //    UserInfo userInfo = new UserInfo();
        //    string logintype = "";
        //    if (!string.IsNullOrEmpty(objUS.SV_VCLoginType))
        //        logintype = objUS.SV_VCLoginType.ToString();
        //    if (!string.IsNullOrEmpty(objUS.SV_VCUserContentID))
        //        userInfo.loginid = int.Parse(objUS.SV_VCUserContentID.ToString());
        //    else
        //        userInfo.loginid = 0;
        //    userInfo = UserDbWEBModel.getUserInfo(userid, 1, logintype, userInfo.loginid);
        //    userInfo.userid = userid;
        //    if (!string.IsNullOrEmpty(objUS.SV_VCUserContentID))
        //        userInfo.loginid = int.Parse(objUS.SV_VCUserContentID.ToString());
        //    else
        //        userInfo.loginid = 0;
        //    int i = 0, p = 0;
        //    if (userInfo.userDetailPercentage.Count >= 1)
        //    {

Views/UserDashboardWEB/UploadImage.cshtml
@model Vconnect.Models.UserDashboardWebModel

 @using Vconnect.Common.HtmlHelpers;
@{
    
    ViewBag.Title = "Image uploader";
   // Layout = "~/Views/Shared/_userdashboardmaster.cshtml";
}
@*<link href="~/Content/ImageArea.css"  rel="stylesheet" />*@

<script src="~/Scripts/WEBScripts/jquery-1.8.2.min.js"></script>
<link href="~/Content/WEBthemes/UserDashbaord/ImageArea.css" rel="stylesheet" />

<script src="~/Scripts/WEBScripts/UserDashboard/jquery.imgareaselect.js"></script>


<script>
    $(document).ready(function () {
        $('.imgareaselect-outer').css({ "display": "none" });
        $('.imgareaselect-handle').css({ "display": "none" });
        debugger;
        $("#cross").click(function () {
            //$('#preview').unload();
            $('.imgareaselect-outer').css({ "display": "none" });
            $('.imgareaselect-handle').css({ "display": "none" });
         document.location = '@Url.Action("UserDetailsWEB","UserDashboardWEB")';

            //document.getElementById('f').style.display = 'none';

        });

        $("#preview").hide();


        //Get the preview image and set the onload event handler
        var preview = $('#preview').load(function (e) {
           // alert("1");
            debugger;
            setPreview();
            ias.setOptions({
                x1: 100,
                y1: 100,
                x2: $(this).width(),
                y2: $(this).height(),
                show: true
            });
            // $('#preview').unload();
            //e.preventDefault();
        });

        var boxes = $('input[type=checkbox]').attr('disabled', true);

        //Set the 4 coordinates for the cropping
        var setPreview = function (x, y, w, h) {
           //  alert("2");
            $('#X').val(x || 0);
            $('#Y').val(y || 0);
            $('#Width').val(w || preview[0].naturalWidth);
            $('#Height').val(h || preview[0].naturalHeight);
        };

        //Initial state of X, Y, Width and Height is 0 0 1 1
        setPreview(10, 10, 11, 11);

        //What happens if the File changes?
        $('#File').change(function (evt) {
          //  alert("3");
            // debugger;
           
            var f = evt.target.files[0];
            var reader = new FileReader();


            if (!f.type.match('image.*')) {
                alert("The selected file does not appear to be an image.");
                return;
            }

            else if (f.size > 4100000) {
                alert("Image size is too great....select image below 4MB");
                $('button').attr('disabled', true)
                return;
            }
            else {
                setBox('#IsFile');
                reader.onload = function (e) {
                    preview.attr('src', e.target.result);
                };

                reader.readAsDataURL(f);

                $("#preview").show();
                document.getElementById("save").style.display = "block";
            }



            //  evt.preventDefault();
        });
        //Check one of the checkboxes
        var setBox = function (filter) {
           // alert("4");
            $('button').attr('disabled', false);
            boxes.attr('checked', false)
            .filter(filter).attr({ 'checked': true, 'disabled': false });
        };

        //What happens if any checkbox is checked ?!
        //boxes.change(function (e) {

        //    setBox(this);
        //    $('#' + this.id.substr(2)).change();
        //    e.preventDefault();
        //});


        //Initialize the image area select plugin
        var ias = preview.imgAreaSelect({

            handles: true,
            instance: true,
            parent: 'body',
            onSelectEnd: function (s, e) {
                //("5");
                // alert(e);

                var scale = preview[0].naturalWidth / preview.width();
                var _f = Math.floor;
                //  alert(_f);
                // alert(scale);
                setPreview(_f(scale * e.x1), _f(scale * e.y1), _f(scale * e.width), _f(scale * e.height));
                //alert(_f(scale * e.width));
                //alert(_f(scale * e.height));
            }
        });
        document.getElementById("save").style.display = "none";
        $('form').submit(function (e) {
            $('button').attr('disabled', true).text('Please wait ...');

            //e.preventDefault();
        });

    });
</script>
   <style>
        #f{
    width:100%;
    top:0;
    left:0;
    right:0;
    bottom:0; 
    position:fixed; 
    z-index:99;
    background:url(@Vconnect.Common.MyGlobalVariables.Staticimage/UserDashboard/blk-bg.png);
}
    .black_overlay
		{
			display: none;
			position: fixed;
			top: 0%;
			left: 0%;
			width: 100%;
			height: 100%;
			background-color: #000;
			z-index: 999999;
			-moz-opacity: 0.8;
			opacity: .80;
			filter: alpha(opacity=80);
		}
      .pop-head
       {
            width: auto;
            height: 30px;
            background: none repeat scroll 0% 0% rgb(243, 243, 243);
            border-bottom: 1px solid rgb(204, 204, 204);
            font-size: 16px;
            font-family: Tahoma,Calibri,Arial;
            padding-top: 5px;
            padding-right: 3px;
            line-height: 25px;
            color: rgb(51, 51, 51);
            padding-left: 10px;
       }
       .upload-text
       {
            color: rgb(174, 174, 174);
            font-family: Tahoma,Arial,Verdana;
            font-size: 12px;
       }
    </style>

 
 
@using (Html.BeginForm("UploadImage", "UserDashboardWeb", FormMethod.Post, new { enctype = "multipart/form-data",id="f" }))
{
    
    @Html.HiddenFor(model => model.X)
    @Html.HiddenFor(model => model.Y)
    @Html.HiddenFor(model => model.Width)
    @Html.HiddenFor(model => model.Height)
    
    <div id="upload-cut"  style="width:100%;" >
    <div class="," style="background-color:white; border:solid; width:600px;position: absolute;top: 15%; left:23%;min-height:300px;" >
        <div class="pop-head">
            Edit Profile Picture 
        <div class="cross-bt" style="float:right;"><a id="cross" href="javascript:void(0)"><img src="@Vconnect.Common.MyGlobalVariables.Staticimage/UserDashboard/cross-bt.png" /></a></div>
            </div>
           @if (ViewBag.message != null)
                {
                    if (ViewBag.message == "Image must be at least 250px in width and height")
                    {
                        <span style="display:block;color:red;">@ViewBag.message</span>
                    }
                    
                }
         <div style="float:left; padding:20px 20px;">
         <div style="float:left;">
            <div class="editor-label ">
               @* @Html.EditorFor(model => model.IsFile)*@
                @Html.LabelFor(model => model.File)
            </div><div class="editor-field ">
                @Html.FileFor(model => model.File)
                @Html.ValidationMessageFor(model => model.File)
            </div>
        </div>
         <div style="clear:both;"></div>
         <div class="upload-text" style="padding-top:50px;">
            JPG/PNG formats only
        </div>
         <div class="upload-text">
            Maximum size 4 MB
        </div>
         <div class="upload-text">
            Greater than 250px in height and width
        </div>
         </div>

        <div  style="float:left;margin-left:60px">
        <div id="upload-cut1"  >
        <img alt="Field for image cutting" id="preview" src=""  style="height:200px;width:200px; margin-top:20px;"/>
        </div>
        </div>
        <div style="clear:both;"></div>
       
       <div style="padding:20px 20px 20px 240px;"> <button type="submit" name="submit" class="work" id="save">Save</button></div>
        @*<button type="submit" name="submit" class="work">Delete</button>*@
    
        <div id="fade" class="black_overlay">
			</div>
    </div>
   
         </div>
 
} 

Views/UserDashboardWEB/_notification.cshtml
@model Vconnect.Models.profilemodel
<script type="text/javascript">
    function getPartialnotification() {
        debugger;
        var arr='';
        var arrChkBox = document.getElementsByName("notIdList");
        debugger;
        for (var k = 0; k < arrChkBox.length;k++) {
            var cmpchk= arrChkBox[k].value.replace('a_','');
            var chkid1 = "chk_" + arrChkBox[k].value.replace('a_','').replace('b_','');
            var a=chkid1.replace('chk_','');
            var b=cmpchk.replace('a_','');
            if (a==b) {
                arr += ',' + arrChkBox[k].value.replace('a_','');
            }
        }
 
        $.getJSON('@Url.Action("NotificationUserDashboard", "UserDashboardWEB")', { notIdList: arr },
                     function (data) {
                         debugger;
                         document.getElementById('message1').innerHTML = "";                             
                         if (data == "0") {
                             document.getElementById('message1').style.marginTop = '-118px';
                             document.getElementById('divnotification').style.paddingTop = "42px";           
                             //document.getElementById('message1').innerHTML = '<div data-alert class="alert-box" style="background-color: green;">Notifications Updated Successfully.<a href="javascript:void(0)" class="close" onclick="displayNT()">&times;</a></div>';
                             document.getElementById('message1').innerHTML ='<div class="alert-box success" data-alert=""> Notifications Updated Successfully <a href="javascript:void(0)" class="close" onclick="displayNT()">&times;</a></div>';
                         }
                         else {
                             document.getElementById('message1').style.marginTop = '-118px';
                             document.getElementById('divnotification').style.paddingTop = "42px";
                             //document.getElementById('message1').innerHTML = '<div data-alert class="alert-box error" style="background-color: #D22C25;">Some error occured Please try again later.<a href="javascript:void(0)" class="close" onclick="displayNT()">&times;</a></div>';
                             
                             document.getElementById('message1').innerHTML = '<div class="alert-box error" data-alert="">Some error occured Please try again later.<a href="javascript:void(0)" class="close" onclick="displayNT()">&times;</a></div>';
                         }
                         document.getElementById('message1').style.display = 'block';
                         //document.getElementById('divnotification').style.paddingTop = "0px";
                     });
    }
    function displayNT() {
        document.getElementById('message1').style.display = 'none';
        document.getElementById('divnotification').style.paddingTop = "10px";
    }
    </script>
<script>
    function fnchecked(id) {
        var chkid = "chk_" + id;
        var cmpchk= "a_" + id;
        var cmpchk0= "b_" + id;
        debugger;
        if (document.getElementById(chkid).value == cmpchk)
            document.getElementById(chkid).value = cmpchk0;
        else
            document.getElementById(chkid).value = cmpchk;
    }
</script>
<div class="row">
                   <div class="alerts" id="message1" style="position: relative;">  
         </div>   
      </div>  
@*<form action="./save-settings">*@
@*    <strong class="title">Social</strong><br/>*@
@if (Model != null)
                        {
                            if(Model.IsErr==0)
                            {
                                foreach (Vconnect.Models.ListUserNotificationsModel UN in Model.listNotifications)
                                {
                                    if (UN.CategoryId.ToString().Trim() == "1")
                                    {
                                                if (UN.IsActive == 1)
                                                {
                                                    <label><input type="checkbox" name="notIdList" checked="checked" value="a_@UN.ContentId" onclick="fnchecked(@UN.ContentId);" id="chk_@UN.ContentId"/> &nbsp;@UN.Notifications</label>
                                                }
                                                else
                                                {
                                                    <label><input type="checkbox" name="notIdList"  value="b_@UN.ContentId" onclick="fnchecked(@UN.ContentId);" id="chk_@UN.ContentId"/> &nbsp;@UN.Notifications</label>
                                                }                             
                                    }
                                }
                            }

                        }
@*<strong class="title">Reminders & updates</strong><br/>*@
         @if (Model != null)
                                {
                                     if(Model.IsErr==0)
                                    {
                              
                                        foreach (Vconnect.Models.ListUserNotificationsModel UN in Model.listNotifications)
                                        {
                                            if (UN.CategoryId.ToString().Trim() == "2")
                                            {
                                                            if (UN.IsActive == 1)
                                                            {
                                                                <label><input type="checkbox" name="notIdList" value="a_@UN.ContentId" checked="checked" id="chk_@UN.ContentId" onclick="fnchecked(@UN.ContentId);"/> &nbsp;@UN.Notifications</label>
                                                            }
                                                            else
                                                            {
                                                                <label><input type="checkbox" name="notIdList" value="b_@UN.ContentId" onclick="fnchecked(@UN.ContentId);" id="chk_@UN.ContentId"/> &nbsp;@UN.Notifications</label>
                                                            }
                                            }
                                        }
                                    }

                                }	
									<button type="submit" onclick="javasript:getPartialnotification();">Save</button>
								@*</form>*@

Views/UserDashboardWEB/_settingprofile.cshtml
@model Vconnect.Models.profilemodel

							<div class="row">
									<div class="columns medium-12">
										<div class="userpic-container">
											<div class="userpic-inner">
												<img src="../img/lab-profile.jpg" alt="profile picture" class="userpic-thumb">
												<div class="pic-loading"></div>
											</div>
											<div class="userpic-upload-inner">
												<div class="image-upload-wrapper">
													<form action="./image-upload" class="dropzone">
														<div class="dz-message">
				                      <span>Change image</span>
				                    </div>
				                    <div class="fallback">
				                      Select a photo: <input type="file">
				                    </div>
													</form>
												</div>
												<span class="muted">JPG, PNG, GIF, less than 5MB</span>
											</div>
										</div>
									</div>
								</div>
								<form method="post" data-abide>
									<div class="row">
										<div class="columns medium-6">
											<label for="fname">First Name <small>Required</small></label>
                                             @Html.TextBoxFor(model => model.txtfname, new { id = "fname", @maxlength = "50", @placeholder = "First Name", @data_invalid = "", @required = "" })											
											<small class="error">Enter your first name</small>
										</div>
										<div class="columns medium-6">
											<label for="sname">Surname <small>Required</small></label>
                                            @Html.TextBoxFor(model => model.txtsname, new { id = "sname", @maxlength = "50", @placeholder = "Surname", @data_invalid = "", @required = "" })
                                            <small class="error">Enter your surname</small>
										</div>
									</div>
									<div class="row">
										<div class="columns medium-6">
											<label for="age">Your Birthday</label>
                                             @Html.TextBoxFor(model => model.txtdob, new { id = "age", @maxlength = "50", @placeholder = "Your birthday .e.g. 13/5/2013"})
                                           @* @Html.TextBoxFor(model => model.txtdob, new { id = "age",@class="datepicker", @maxlength = "50", @placeholder = "Your birthday .e.g. 13/5/2013" })*@
											@*<input id="age" class="datepicker" type="text" placeholder="Your birthday .e.g. 13/5/2013">*@
										</div>
										<div class="columns medium-6">
											<label for="sex">Sex</label>
                                             @Html.DropDownListFor(model => model.SelectgenderId, Model.genderoption, "Please Select", new { @id = "sex", @placeholder = "State"})
											@*<select name="sex" id="sex">
												<option value="">Please Select</option>
												<option value="male">Male</option>
												<option value="female">Female</option>
											</select>*@
										</div>
									</div>
									<div class="row">
										<div class="columns medium-6">
											<label for="state">Your State</label>
                                            @Html.DropDownListFor(model => model.SelectedStateId, Model.StateOptions, "Please Select", new { @id = "drp1", @placeholder = "State"})
											@*<select name="state" id="state">
												<option value="">Please Select</option>
												<option value="lag">Lagos</option>
												<option value="ph">Portharcourt</option>
											</select>*@
										</div>
										<div class="columns medium-6">
											<label for="lga">Your Local Government</label>
                                            @Html.DropDownListFor(model => model.SelectedCityId, Model.CityOptions, "Please select", new { @id = "drp2", @placeholder = "Local Government Area"})
											@*<select name="lga" id="lga">
												<option value="">Please Select</option>
												<option value="ow">Owan</option>
												<option value="su">Surulere</option>
											</select>*@
										</div>
									</div>
									<div class="row">
										<div class="columns medium-6">
											<label for="phone" id="pcl">Phone Number</label>
                                                @Html.TextBoxFor(model => model.txtphone, new { id = "phonenumber",@style="margin-bottom:0px;", onkeypress = "return isNumberKey(event)", maxlength = "11", @placeholder = "Contact Number", @onfocus = "this.placeholder = ''", @onblur = "this.placeholder = 'Phone Number e.g. 07127852835'", @data_invalid = "", @required = "", @pattern = "mobile" })
                                                <small id="Msgavailablebusinessphoneno" class="error" style="margin-bottom:0px; color:white;">Enter phone number</small>       
                                                @* <div class="errordiv" id="Msgavailablebusinessphoneno" style="display: none;"></div>*@
                                                <div id="Msgavailablebusinessphonenol" style="display: none;">
                                                <img src="~/Images/WEB/logos/allpageloader.gif" alt="Processing..." />
                                                <div class="bizuser_loadertxt">
                                                <label id="Labelloaderphone">
                                                </label>
                                                </div>
                                                </div>
                                                <div id="divnf2" class="Msgavailablebusiness"></div>   
											@*<input id="phone" type="text" placeholder="Phone Number e.g. 07127852835">*@
										</div>
										<div class="columns medium-6">
											<label for="bio">Your Bio</label>
                                            @Html.TextAreaFor(model => model.txtdescription, new { id = "bio",@cols="30",@rows="10", @placeholder = "A little description about yourself...", @style = "min-height:100px;"})
											@*<textarea name="bio" id="bio" cols="30" rows="10" placeholder="A little description about yourself..."></textarea>*@
										</div>
									</div>
									<div class="row">
										<div class="columns medium-12 text-right">
                                            <input type="Submit" value="Save" class="button small"/>
										</div>
									</div>
								</form>	

Views/UserDashboardWEB/share.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>share</title>
</head>
<body>
    <div>
        
    </div>
</body>
</html>